mochajs/mocha-examples

packages/typescript/README.md

When building a typescript project with typescript compiler options for `module` set to anything except `commonjs`, mocha tests will fail when you attempt to do an `import` in your code. Figuring out why was non-trivial, and probably worthy of a note here in the README to forewarn people who end up on this path, and provide a workaround.
More discussion on the underlying issue of ts-node (and node) not supporting ES modules is found here:
- https://github.com/TypeStrong/ts-node/issues/212
- https://github.com/TypeStrong/ts-node/issues/182

Add tips for testing with ES Modules

---

package.json

For cleaning up all dependencies and reinstalling them, add `lerna clean` as a npm script.

add npm script to remove all node_modules

---

packages/async-setup-with-delay/package-lock.json
packages/async-setup-with-delay/package.json
packages/async-setup-with-file/package-lock.json
packages/async-setup-with-file/package.json
packages/babel/package-lock.json
packages/babel/package.json
packages/express-rest-api/package-lock.json
packages/express-rest-api/package.json
packages/karma/package-lock.json
packages/karma/package.json
packages/programmatic-usage/package-lock.json
packages/programmatic-usage/package.json
packages/puppeteer/package-lock.json
packages/puppeteer/package.json
packages/react-webpack/package-lock.json
packages/react-webpack/package.json
packages/selenium/package-lock.json
packages/selenium/package.json
packages/third-party-reporter/package-lock.json
packages/third-party-reporter/package.json
packages/typescript-babel/package-lock.json
packages/typescript-babel/package.json
packages/typescript/package-lock.json
packages/typescript/package.json
packages/vue-puppeteer/package-lock.json
packages/vue-puppeteer/package.json

When we release new mocha version, we should update the versions here.
IMO, this examples should run with mocha's latest version. Otherwise, we should realize it. 
So, use `mocha@latest` here is better for us.

Use mocha@latest instead specific version

---

packages/express-rest-api/package.json
packages/express-rest-api/server/app.js
packages/express-rest-api/server/index.js

`#!/usr/bin/env node` doesn't support  on No Unix-like platforms.
So, to support operating systems such as Windows, I think you need to run the file using a node.
Also, I removed `path` because `app.js` didn't use  it.
Any comments are welcome everytime!!
I was able to learn well thanks to good examples :)

Change express rest api start comamnd

---

packages/typescript/package-lock.json

When running `npm install` for the `typescript` example npm reports 4 vulnerabilities (2 high). All of those can be fixed by running `npm audit fix`, which I did. The commit contains just the updated `package-lock.json` file.
These vulnerabilities are probably not that relevant in this context, but this way there are no error-like (red) messages in the install log, which is nice :)

TypeScript example: npm audit fix

---

packages/programmatic-usage/package.json
packages/selenium/package-lock.json
packages/selenium/package.json

I couldn't find the history, but npm doesn't seem to expose `npm_package_directories_test` env vars anymore.
In npm@v6, `npm_package_directories_test` was exposed and our CI still uses npm@v6.

npm@v7 doesn't seem to expose `npm_package_directories_test`

---

.github/workflows/test.yml

[GitHub now support it](https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/).

Remove CI-SKIP on GitHub Actions

---

.github/workflows/test.yml

* Match node versions with mocha repository 
* Run test every week because this repository is not actively changed, so sometimes we didn't realize tests are broken.

match node version and run tests periodically

---

.github/workflows/test.yml

Because `selenium-webdriver` has a bug with Node 18, Node 18 in our CI tests will be disabled until `selenium-webdriver`'s new release include [the fix](https://github.com/SeleniumHQ/selenium/pull/10611).

Disable tests with Node 18 temporarily

---

packages/react-webpack/package.json

Because of cheerio in enzyme, our example-react-webpack-app is broken. So, I pin cherrio version for Enzyme.js. See https://github.com/enzymejs/enzyme/issues/2558
```
example-react-webpack-app: Error: Package subpath './lib/utils' is not defined by "exports" in /home/runner/work/mocha-examples/mocha-examples/packages/react-webpack/node_modules/cheerio/package.json
example-react-webpack-app:     at new NodeError (node:internal/errors:372:5)
example-react-webpack-app:     at throwExportsNotFound (node:internal/modules/esm/resolve:472:9)
example-react-webpack-app:     at packageExportsResolve (node:internal/modules/esm/resolve:753:3)
example-react-webpack-app:     at resolveExports (node:internal/modules/cjs/loader:482:36)
example-react-webpack-app:     at Function.Module._findPath …
```

deps: pin cherroio to avoid a error

---

packages/puppeteer/test/index.spec.js

> waitFor is deprecated and will be removed in a future release. See https://github.com/puppeteer/puppeteer/issues/6214 for details and how to migrate your code.
Fix a deprecated warning.

puppeteer: fix deprecated waitFor

---

package.json

Lerna is now maintained by Nwrl. So, we should use [v5](https://github.com/lerna/lerna/releases/tag/v5.0.0) even if there is no significant improvement and performance.

deps: update lerna to v5

---

.github/workflows/test.yml
packages/selenium/package.json

In #52 selenium-driver was not compatible with Node 18.
This bug was fixed in https://github.com/SeleniumHQ/selenium/pull/10611 and included in [selenium-driver 4.2.0](https://github.com/SeleniumHQ/selenium/releases/tag/selenium-4.2.0).

selenium: update driver to make compatible with node 18

---

packages/selenium/package.json

GH Actions user 104.0.5, but chromedriver has been updated to 105.0.0.
```
example-selenium-app:        "before each" hook for "should render a message on a Google search result":
example-selenium-app:      SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 105
example-selenium-app: Current browser version is 104.0.5[112](https://github.com/mochajs/mocha-examples/runs/8207049839?check_suite_focus=true#step:7:113).101 with binary path /usr/bin/google-chrome
example-selenium-app:       at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:522:15)
example-selenium-app:       at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:589:13)
example-selenium-app:       at Executor.execute …
```

Set chromedriver version to 104

---

.github/workflows/test.yml

We don't have any `package-lock.json`.

ci: fix wrong cache key

---

package-lock.json
packages/hello-world/package-lock.json
packages/typescript-ts-node-esm-loader/.gitignore
packages/typescript-ts-node-esm-loader/.mocharc.json
packages/typescript-ts-node-esm-loader/README.md
packages/typescript-ts-node-esm-loader/package-lock.json
packages/typescript-ts-node-esm-loader/package.json
packages/typescript-ts-node-esm-loader/src/index.spec.ts
packages/typescript-ts-node-esm-loader/src/index.ts
packages/typescript-ts-node-esm-loader/tsconfig.json

I noticed there wasn't yet an example that shows TypeScript transpilation on-the-fly with ESM imports/loaders. https://github.com/mochajs/mocha/issues/5002 is a Mocha issue asking about support.
This adds two examples:
* `--import=tsx/esm`: Newer `--import` flag for Node.js post-v18.19.0/v20.6.0
* `--loader=ts-node/esm`: Older `--loader` flag for Node.js
Fixes #75

feat: added TypeScript + ts-node/esm and tsx/esm examples

---

.github/workflows/test.yml

chore: run 'npx playwright install' in CI

---

.github/workflows/test.yml

chore: bump CI Node versions to 18, 20, and 22 (LTS)

---

README.md
packages/global-fixture/README.md
packages/global-fixture/fixture.js
packages/global-fixture/package.json
packages/global-fixture/test.spec.js

Adds a fixture that exercises both _setup_ and _teardown_, as an example.

feat: added global-fixture example

---

packages/third-party-reporter/README.md
packages/third-party-reporter/index.js
packages/third-party-reporter/test/unit/my-reporter.spec.js

- Link to more comprehensive API and tutorial docs (not the GitHub wiki, as that's outdated)
- Add sample failing test

fix: Improve third-party reporters example
